---
- name: reboot the server
  command: sleep 2 && reboot -r now
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for SSH port down
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: stopped
  delegate_to: localhost

- name: wait for SSH port up
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 30
  delegate_to: localhost
