---
- include_vars: vars/main.yml

- name: add OpenNebula Repository Key
  apt_key:
    url: https://downloads.opennebula.org/repo/repo.key
    state: present

- name: add OpenNebula Repository (Debian 8)
  apt_repository:
    filename: opennebula
    repo: deb https://downloads.opennebula.org/repo/5.4/Debian/8 stable opennebula
    update_cache: yes
    state: present
  when: "ansible_distribution == 'Debian' and ansible_distribution_major_versio == '8'"

- name: add OpenNebula Repository (Debian 9)
  apt_repository:
    filename: opennebula
    repo: deb https://downloads.opennebula.org/repo/5.4/Debian/9 stable opennebula
    update_cache: yes
    state: present
  when: "ansible_distribution == 'Debian' and ansible_distribution_major_version == '9'"

- name: add OpenNebula Repository (Ubuntu 14.04)
  apt_repository:
    filename: opennebula
    repo: deb https://downloads.opennebula.org/repo/5.4/Ubuntu/14.04 stable opennebula
    update_cache: yes
    state: present
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'"

- name: add OpenNebula Repository (Ubuntu 16.04)
  apt_repository:
    filename: opennebula
    repo: deb https://downloads.opennebula.org/repo/5.4/Ubuntu/16.04 stable opennebula
    update_cache: yes
    state: present
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'"

- name: add OpenNebula Repository (Ubuntu 17.04)
  apt_repository:
    filename: opennebula
    repo: deb https://downloads.opennebula.org/repo/5.4/Ubuntu/17.04 stable opennebula
    update_cache: yes
    state: present
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_version == '17.04'"

- name: install OpenNebula Front-end
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - opennebula
    - opennebula-sunstone
    - opennebula-gate
    - opennebula-flow
